name = "BuildCLI"
uuid = "31b36b5f-c418-4d09-b0d5-480756067249"
authors = ["Anup Joseph <anup20joseph@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
